# Project: PLA
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Tuple.o Unused.o
LINKOBJ  = main.o Tuple.o Unused.o
LIBS     = -L"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/lib" -L"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/include" -I"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/include" -I"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/Software/Setupbags/Dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = PLA.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Tuple.o: Tuple.cpp
	$(CPP) -c Tuple.cpp -o Tuple.o $(CXXFLAGS)

Unused.o: Unused.cpp
	$(CPP) -c Unused.cpp -o Unused.o $(CXXFLAGS)
